In [8]:
# !conda install -c conda-forge tiledb
# !conda install -c conda-forge tiledb-py

In [9]:
import tiledb
import numpy as np

In [10]:
tiledb.__version__

'0.11.2'

In [11]:
tiledb.libtiledb.version()

(2, 5, 2)

## 2D array

In [15]:
# Create dimensions
d1 = tiledb.Dim(name="d1",domain=(1,4),tile=2, dtype = np.int32)
d2 = tiledb.Dim(name="d2",domain=(1,4),tile=2, dtype = np.int32)

# Create domain using the two dimensions
dom1 = tiledb.Domain(d1,d2)

# Create attribute
a = tiledb.Attr(name="a", dtype= np.int32)

# Create the array schema, spare = False to indicate a dense array
schema1 = tiledb.ArraySchema(domain=dom1, sparse=False, attrs=[a])

# Create the array on disk ( it will be intially empty )
tiledb.Array.create("dense_array1",schema1)

In [18]:
!tree dense_array1

dense_array1
├── __lock.tdb
├── __meta
└── __schema
    └── __1637267278772_1637267278772_6c150466aff54b51943f6b87bd2aa447

2 directories, 2 files


In [17]:
schema = tiledb.ArraySchema.load("dense_array1")
schema

ArraySchema(
  domain=Domain(*[
    Dim(name='d1', domain=(1, 4), tile='2', dtype='int32'),
    Dim(name='d2', domain=(1, 4), tile='2', dtype='int32'),
  ]),
  attrs=[
    Attr(name='a', dtype='int32', var=False, nullable=False),
  ],
  cell_order='row-major',
  tile_order='row-major',
  capacity=10000,
  sparse=False,
)

In [19]:
data = np.array([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,16]],dtype=np.int32)
data

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 1,  2,  3, 16]], dtype=int32)

In [20]:
with tiledb.open("dense_array1",'w') as A:
    A[:] = data

In [21]:
!tree dense_array1

dense_array1
├── __1637341314611_1637341314611_ee145f5445cb4bd287a4cf0277172ddf_10
│   ├── __fragment_metadata.tdb
│   └── a0.tdb
├── __1637341314611_1637341314611_ee145f5445cb4bd287a4cf0277172ddf_10.ok
├── __lock.tdb
├── __meta
└── __schema
    └── __1637267278772_1637267278772_6c150466aff54b51943f6b87bd2aa447

3 directories, 5 files


In [22]:
with tiledb.open("dense_array1",'r') as A:
    print(A[:]["a"])

[[ 1  2  3  4]
 [ 1  2  3  4]
 [ 1  2  3  4]
 [ 1  2  3 16]]


In [24]:
with tiledb.open("dense_array1",'r') as A:
    print(A[1:3]["a"])

[[1 2 3 4]
 [1 2 3 4]]


In [ ]:
with tiledb.open("dense_array1",'r') as A:
    print(A[1:3]["a"])